name: Deploy Expo Web to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Expo Web App
        run: npx expo export --platform web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAT }}   # ✅ Use a personal access token
          publish_dir: ./web-build                 # ✅ Matches Expo SDK 54 output
          force_orphan: true                       # ✅ Ensures clean gh-pages branch
